/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/clients` | `/clients`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/incomes` | `/incomes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/products` | `/products`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/regular-orders` | `/regular-orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sales` | `/sales`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stock` | `/stock`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/summary` | `/summary`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orders/[id]` | `/orders/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/clients` | `/clients`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/incomes` | `/incomes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/products` | `/products`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/regular-orders` | `/regular-orders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/sales` | `/sales`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stock` | `/stock`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/summary` | `/summary`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/orders/[id]` | `/orders/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/account${`?${string}` | `#${string}` | ''}` | `/account${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/clients${`?${string}` | `#${string}` | ''}` | `/clients${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/incomes${`?${string}` | `#${string}` | ''}` | `/incomes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/orders${`?${string}` | `#${string}` | ''}` | `/orders${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/products${`?${string}` | `#${string}` | ''}` | `/products${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/regular-orders${`?${string}` | `#${string}` | ''}` | `/regular-orders${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/sales${`?${string}` | `#${string}` | ''}` | `/sales${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stock${`?${string}` | `#${string}` | ''}` | `/stock${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/summary${`?${string}` | `#${string}` | ''}` | `/summary${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/clients` | `/clients`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/incomes` | `/incomes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/products` | `/products`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/regular-orders` | `/regular-orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sales` | `/sales`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stock` | `/stock`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/summary` | `/summary`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}/orders/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/orders/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(tabs)'}/orders/[id]` | `/orders/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
